//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Integrante = new HashSet<Integrante>();
        }

        public int id { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Salario")]
        public double salario { get; set; }
        [DisplayName("Horario")]
        public string horario { get; set; }
        [DisplayName("Proyecto")]
        public int Proyecto_id { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<Integrante> Integrante { get; set; }
    }
}
