//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.Recurso_Tarea = new HashSet<Recurso_Tarea>();
        }

        public int id { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Cantidad")]
        public int cantidad { get; set; }
        [DisplayName("Ubicacion")]
        public string ubicacion { get; set; }
    
        public virtual ICollection<Recurso_Tarea> Recurso_Tarea { get; set; }
    }
}
