//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Recurso_Tarea
    {
        public int id { get; set; }
        [DisplayName("Cantidad")]
        public int cantidad { get; set; }
        [DisplayName("Actividad")]
        public int Actividad_id { get; set; }
        [DisplayName("Tarea")]
        public int Tarea_id { get; set; }
        [DisplayName("Recurso")]
        public int Recurso_id { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Recurso Recurso { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
