//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Integrante = new HashSet<Integrante>();
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public int id { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int edad { get; set; }
        public string telefono { get; set; }
        public string usuario1 { get; set; }
        public string contrasenia { get; set; }
        public string correo { get; set; }
        public int Tipo_Usuario { get; set; }
    
        public virtual ICollection<Integrante> Integrante { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario1 { get; set; }
    }
}
